services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      -POSTGRES_PASSWORD: rox
      -POSTGRES_USER: postgres
      -POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    
       
        